apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: gcr.io/snapshot/test:latest
        name: node-app
        ports:
        - containerPort: 3000

---

kind: Service
apiVersion: v1
metadata:
  name: node-app
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
